### ISSUE TITLE
解析NOE77101中的385时无法正确显示密码

### ISSUE THREAD

**Issue by PSoul** [dark-lbp/vxhunter#1]
![image](https://user-images.githubusercontent.com/6669008/61191590-d5b6fa80-a6de-11e9-929d-d6a478f9a4dd.png)

左边是用vxhunter自动解析的，右边是手动拿脚本处理出来的，可以看见右边可以直接把硬编码输出成字符串，但是左边对应的还是一个地址，需要去地址里看每个byte，请问用vxhunter解析能做成右边的效果吗，如果能应该怎么做

**Comment by dark-lbp** [comment]
VxHunter的IDA插件本身依赖IDA对字符串的解析，所以左图中的原因是IDA没有正确识别这部分的字符串。解决办法是找到这个字符串的位置，然后用VxHunter中的`Fix ascii string`功能，对这部分的字符串进行自行识别。
![image](https://user-images.githubusercontent.com/3477662/61671080-b0e30880-ad18-11e9-8724-440be2ebd7dd.png)
识别完成后在IDA中j就可以真确的显示这些数据了。
![image](https://user-images.githubusercontent.com/3477662/61671149-e0921080-ad18-11e9-8637-973269538dd0.png)

**Comment by dark-lbp** [comment]
我要关闭这个issue了，如果你还有什么问题的话，可以在这里回复。
